name: Build and Publish Python Package

on:
  push:
  release:
    types:
      - created

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.x

  #     - name: Install dependencies
  #       run: |
  #         pip install --upgrade setuptools wheel twine pytest hdstats odc-algo
  #         pip install -e .

  #     - name: Run tests
  #       run: |
  #         pytest .

  build:
    runs-on: ubuntu-latest
    # needs: test
    # if: github.event_name == 'release'
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        run: |
          pip install --upgrade setuptools wheel twine

      - name: Build and publish Python package
        uses: RalfG/python-wheels-manylinux-build@v0.7.1-manylinux2010_x86_64
        with:
          python-versions: 'cp310-cp310 cp311-cp311 cp312-cp312'
          build-requirements: 'setuptools'
          system-packages: 'rust-toolset'

      - name: Get version number for tagging the image
        id: get_version
        run: |
          git fetch --all --tags
          echo "VERSION=$(git describe --tags)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          '${{ steps.get_version.outputs.VERSION }}'
          --repo '${{ github.repository }}'
          --notes ""

      - name: Upload artifact signatures to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release upload
          '${{ steps.get_version.outputs.VERSION }}' dist/**
          --repo '${{ github.repository }}'
